# This is a basic workflow to help you get started with Actions
name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  env:
    NODE_OPTIONS: --openssl-legacy-provider
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip CI]') }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '17.0.1'
    - run: npm install
    - run: npm run build
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip CI]') }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '17.0.1'
    - run: npm install
    - run: npm run build
    - run: npm run test
